fieldLayouts:
  aa2f56ec-be2f-4366-b912-a48ddfd78b14:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 76d94e3f-53f5-40d2-a603-50d6bb44b943
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6af92e13-3817-4619-a65c-3522d4d1fc67 # Venue
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a89feaa-1397-41b9-8a03-9e6c3492c331
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d0f0616-8e42-42a9-a19f-8738798cff7e # Familiar ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 305dcaa2-4186-48c6-bf88-e7fc97651b6d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 25e903a3-f98e-43b0-badc-fe4a7b8f1b27 # Headset Unique ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd5c02a0-d52b-4109-a460-009400526aac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3aba213d-a73b-437b-a5ef-4f53042fb3e0 # User record stats
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 544d728f-0cf4-4e58-a61a-9081f5e99b5d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c4b384a-0d46-45e9-9ec8-9c0f5a2e223b # User need internet
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5164d39-a472-480b-a695-bd3917e97f6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54ab8604-2b9e-4eb6-9cae-b093124b0e66 # Mode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5482c79-3fe1-4e58-8b9e-3e619b6848f5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17356f99-2ef6-4a3f-88ab-b1cb7d345a80
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 38875b9f-df2c-41e6-a1a2-e9d4ed370735 # Headsets
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
