color: null
fieldLayouts:
  4148225d-9e14-42d3-b0d7-bc884c5588ad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-23T18:53:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fb387136-40af-43f1-a568-fd1c55739db4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T18:53:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6af92e13-3817-4619-a65c-3522d4d1fc67 # Venue
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8829e190-ee8b-4b81-8cfe-7af420e60bf1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T18:53:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d55f6463-5f76-4782-9af7-78a88483b0f0 # Headset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac2eb4f8-a226-4d03-8cdf-f6b491b09170
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T18:53:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cc8877ab-7d30-4e23-b01f-3a8318288fc0 # Movie Name
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d295689-0fd3-4fcd-8d1c-590f349ae258
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T18:53:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f83d583c-7b6a-4dc7-8d00-7bdd51363137 # Visit Language
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f8ad358-8b71-4b44-ba41-7dab38f6deb3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T18:53:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9060c98-f56d-4cca-b4d5-de78d810e775 # Visit Start
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e12f3be3-1f13-4b19-8f67-2b7a49724be9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85c9d681-0307-450c-b273-15a2fc771276
        userCondition: null
handle: default
hasTitleField: true
icon: null
name: Default
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
