fieldLayouts:
  f34af012-d7be-42c8-99fe-b20987d7b77d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3212ee3b-9702-43bb-b2c9-20825de5c4cd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 51f08e6f-f44f-4293-bc27-451451544caa
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b3e8c798-1f09-4ca2-ac30-695d0273d094 # Movies
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
