baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Emagine VR Analytics'
primary: true
siteGroup: 3226293d-1172-4808-9dfa-adbbb8120257 # Emagine VR Analytics
sortOrder: 1
