isPublic: true
name: 'Public Schema'
scope:
  - 'sites.f957802c-8f19-44d3-a30a-668d452862ac:read' # Emagine VR Analytics
  - 'sites.9d44ec00-9f8f-426a-9ff0-3ed368bea372:read' # Emagine Analytics FR
  - 'sections.cb843ec5-3aaa-44ea-94cf-f99f4023642f:read' # Statistics
  - 'usergroups.everyone:read'
