columnSuffix: gkzqjlpu
contentColumnType: text
fieldGroup: 70c63edf-2fc7-463d-bef9-779cc51b7d25 # Common
handle: familiarId
instructions: 'This is what order the headset will appear on the tablet app. Use a number starting from 1 - upwards.'
name: 'Familiar ID'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
