columnSuffix: zoppkacn
contentColumnType: boolean
fieldGroup: 5778bcdf-1965-4d5d-9dfe-4f703a474aae # Movies
handle: isMono
instructions: null
name: 'Is mono'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
