columnSuffix: ilhulyow
handle: isMultiFile
instructions: null
name: 'Multi file'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
