columnSuffix: mxaepfpm
handle: killCode
instructions: null
name: 'Kill code'
searchable: false
settings:
  decimals: 0
  defaultValue: 0
  max: 2
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: 1
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
