columnSuffix: nkfylofw
handle: mode
instructions: null
name: Mode
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Tablet
        -
          - value
          - tablet
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Gaze
        -
          - value
          - gaze
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
