columnSuffix: lcoaswav
contentColumnType: boolean
handle: userNeedInternet
instructions: null
name: 'User need internet'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
