columnSuffix: shoaczci
contentColumnType: boolean
fieldGroup: eb0db3a1-ef42-4db3-9257-bc4574b57570 # headset
handle: userRecordStats
instructions: null
name: 'User record stats'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
