columnSuffix: shoaczci
contentColumnType: boolean
handle: userRecordStats
instructions: null
name: 'User record stats'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
