columnSuffix: lcoaswav
contentColumnType: boolean
fieldGroup: eb0db3a1-ef42-4db3-9257-bc4574b57570 # headset
handle: userNeedInternet
instructions: null
name: 'User need internet'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
