columnSuffix: fruvctol
contentColumnType: text
fieldGroup: eb0db3a1-ef42-4db3-9257-bc4574b57570 # headset
handle: uuid
instructions: null
name: 'Headset Unique ID'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
