columnSuffix: hjwvgxqr
contentColumnType: time
handle: venueClosingTime
instructions: null
name: 'Venue Closing Time'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
