columnSuffix: odumgdut
contentColumnType: 'decimal(12,2)'
fieldGroup: cfe8b169-e903-42f6-92ac-f4af56aa1ab8 # Venues
handle: venueTicketPrice
instructions: null
name: 'Venue Ticket Price'
searchable: false
settings:
  decimals: 2
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
