columnSuffix: akixlfui
contentColumnType: text
fieldGroup: d4460fc8-b976-4652-92d2-7d820d7502ef # Statistics
handle: visitLanguage
instructions: null
name: 'Visit Language'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
