dateModified: 1699807860
email:
  fromEmail: hello@emagine.ie
  fromName: 'Emagine VR Analytics'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    4e940878-c1ee-4493-ba07-9714a5292f0b: 'Stats Schema' # Stats Schema
    6af92e13-3817-4619-a65c-3522d4d1fc67: Venue # Venue
    6e395cf4-c9ab-4960-8c68-62b6bbcf4714: Default # Default
    17e706db-ccd3-4eab-9d3a-e8e5fed9d10a: Default # Default
    32c28836-80b3-4da9-a427-6d42b223613b: Clients # Clients
    70c63edf-2fc7-463d-bef9-779cc51b7d25: Common # Common
    73ccaa0c-844d-46d0-8b58-e33c1baaa8f2: 'Venue Currency Type' # Venue Currency Type
    312b4f06-f575-487d-8777-e646ddb19ba6: 'Venue Ticket Price' # Venue Ticket Price
    349ff4ce-c3d6-401e-a73d-26ef36146dba: 'Company Name' # Company Name
    6107f7f5-b967-4eff-900d-72acac322b28: Users # Users
    38875b9f-df2c-41e6-a1a2-e9d4ed370735: Headsets # Headsets
    0084065a-21dc-4833-9064-d97f4e1c9bca: 'Venue Opening Time' # Venue Opening Time
    3226293d-1172-4808-9dfa-adbbb8120257: 'Emagine VR Analytics' # Emagine VR Analytics
    a7b7e1ba-7fb3-4258-8a31-c45adeaf82b8: Default # Default
    a5255343-5341-4742-9fd7-dc1f26af404a: Admin # Admin
    b3e8c798-1f09-4ca2-ac30-695d0273d094: Movies # Movies
    b748cdca-ffaa-490f-98b0-5fa1c1e70095: 'Company Logo' # Company Logo
    cb843ec5-3aaa-44ea-94cf-f99f4023642f: Statistics # Statistics
    cc7c385a-fa47-48b0-8edb-006e60e4b8f1: 'Venue Closing Time' # Venue Closing Time
    cc8877ab-7d30-4e23-b01f-3a8318288fc0: 'Movie Name' # Movie Name
    cca433bd-c86d-402b-9734-50cc40b8760d: 'Public Schema' # Public Schema
    cfe8b169-e903-42f6-92ac-f4af56aa1ab8: Venues # Venues
    d55f6463-5f76-4782-9af7-78a88483b0f0: Headset # Headset
    d4460fc8-b976-4652-92d2-7d820d7502ef: Statistics # Statistics
    df793da0-9723-422b-a370-2e9c303381d0: Default # Default
    f83d583c-7b6a-4dc7-8d00-7bdd51363137: 'Visit Language' # Visit Language
    f9060c98-f56d-4cca-b4d5-de78d810e775: 'Visit Start' # Visit Start
    f957802c-8f19-44d3-a30a-668d452862ac: 'Emagine VR Analytics' # Emagine VR Analytics
    fa1a9449-1cdb-4185-8017-6d6baea8371b: Venues # Venues
plugins:
  _em-stats:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      languageMap:
        __assoc__:
          -
            - en
            -
              __assoc__:
                -
                  - name
                  - English
                -
                  - color
                  - bg-amber-500
                -
                  - hex
                  - '#f59e0b'
  _venue:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Emagine VR Analytics'
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: Europe/Dublin
