description: ''
handle: admin
name: Admin
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accesssitewhensystemisoff
  - administrateusers
  - 'assignusergroup:32c28836-80b3-4da9-a427-6d42b223613b' # Clients
  - 'assignusergroup:a5255343-5341-4742-9fd7-dc1f26af404a' # Admin
  - assignuserpermissions
  - 'createentries:38875b9f-df2c-41e6-a1a2-e9d4ed370735' # Headsets
  - 'createentries:cb843ec5-3aaa-44ea-94cf-f99f4023642f' # Statistics
  - 'createentries:fa1a9449-1cdb-4185-8017-6d6baea8371b' # Venues
  - 'deleteentries:38875b9f-df2c-41e6-a1a2-e9d4ed370735' # Headsets
  - 'deleteentries:cb843ec5-3aaa-44ea-94cf-f99f4023642f' # Statistics
  - 'deleteentries:fa1a9449-1cdb-4185-8017-6d6baea8371b' # Venues
  - 'deletepeerentries:38875b9f-df2c-41e6-a1a2-e9d4ed370735' # Headsets
  - 'deletepeerentries:cb843ec5-3aaa-44ea-94cf-f99f4023642f' # Statistics
  - 'deletepeerentries:fa1a9449-1cdb-4185-8017-6d6baea8371b' # Venues
  - 'deletepeerentrydrafts:38875b9f-df2c-41e6-a1a2-e9d4ed370735' # Headsets
  - 'deletepeerentrydrafts:cb843ec5-3aaa-44ea-94cf-f99f4023642f' # Statistics
  - 'deletepeerentrydrafts:fa1a9449-1cdb-4185-8017-6d6baea8371b' # Venues
  - deleteusers
  - editusers
  - impersonateusers
  - moderateusers
  - performupdates
  - registerusers
  - 'saveentries:38875b9f-df2c-41e6-a1a2-e9d4ed370735' # Headsets
  - 'saveentries:cb843ec5-3aaa-44ea-94cf-f99f4023642f' # Statistics
  - 'saveentries:fa1a9449-1cdb-4185-8017-6d6baea8371b' # Venues
  - 'savepeerentries:38875b9f-df2c-41e6-a1a2-e9d4ed370735' # Headsets
  - 'savepeerentries:cb843ec5-3aaa-44ea-94cf-f99f4023642f' # Statistics
  - 'savepeerentries:fa1a9449-1cdb-4185-8017-6d6baea8371b' # Venues
  - 'savepeerentrydrafts:38875b9f-df2c-41e6-a1a2-e9d4ed370735' # Headsets
  - 'savepeerentrydrafts:cb843ec5-3aaa-44ea-94cf-f99f4023642f' # Statistics
  - 'savepeerentrydrafts:fa1a9449-1cdb-4185-8017-6d6baea8371b' # Venues
  - 'utility:clear-caches'
  - 'utility:db-backup'
  - 'utility:deprecation-errors'
  - 'utility:find-replace'
  - 'utility:migrations'
  - 'utility:php-info'
  - 'utility:queue-manager'
  - 'utility:system-messages'
  - 'utility:system-report'
  - 'utility:updates'
  - 'viewentries:38875b9f-df2c-41e6-a1a2-e9d4ed370735' # Headsets
  - 'viewentries:cb843ec5-3aaa-44ea-94cf-f99f4023642f' # Statistics
  - 'viewentries:fa1a9449-1cdb-4185-8017-6d6baea8371b' # Venues
  - 'viewpeerentries:38875b9f-df2c-41e6-a1a2-e9d4ed370735' # Headsets
  - 'viewpeerentries:cb843ec5-3aaa-44ea-94cf-f99f4023642f' # Statistics
  - 'viewpeerentries:fa1a9449-1cdb-4185-8017-6d6baea8371b' # Venues
  - 'viewpeerentrydrafts:38875b9f-df2c-41e6-a1a2-e9d4ed370735' # Headsets
  - 'viewpeerentrydrafts:cb843ec5-3aaa-44ea-94cf-f99f4023642f' # Statistics
  - 'viewpeerentrydrafts:fa1a9449-1cdb-4185-8017-6d6baea8371b' # Venues
