defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: 17e706db-ccd3-4eab-9d3a-e8e5fed9d10a # Default
handle: headsets
maxAuthors: 1
name: Headsets
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  f957802c-8f19-44d3-a30a-668d452862ac: # Emagine VR Analytics
    enabledByDefault: true
    hasUrls: true
    template: headsets/_entry
    uriFormat: 'headsets/{slug}'
type: channel
