defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1a26c486-8723-402a-a398-68b766f2d163 # Default
handle: languages
maxAuthors: 1
name: Languages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  f957802c-8f19-44d3-a30a-668d452862ac: # Emagine VR Analytics
    enabledByDefault: true
    hasUrls: true
    template: languages/_entry
    uriFormat: 'languages/{slug}'
type: channel
