defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: a7b7e1ba-7fb3-4258-8a31-c45adeaf82b8 # Default
handle: movies
maxAuthors: 1
name: Movies
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f957802c-8f19-44d3-a30a-668d452862ac: # Emagine VR Analytics
    enabledByDefault: true
    hasUrls: true
    template: movies/_entry
    uriFormat: 'movies/{slug}'
type: channel
