defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: df793da0-9723-422b-a370-2e9c303381d0 # Default
handle: statistics
maxAuthors: 1
name: Statistics
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  f957802c-8f19-44d3-a30a-668d452862ac: # Emagine VR Analytics
    enabledByDefault: true
    hasUrls: true
    template: statistics/_entry
    uriFormat: 'statistics/{slug}'
type: channel
