defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: 6e395cf4-c9ab-4960-8c68-62b6bbcf4714 # Default
handle: venues
maxAuthors: 1
name: Venues
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  f957802c-8f19-44d3-a30a-668d452862ac: # Emagine VR Analytics
    enabledByDefault: true
    hasUrls: true
    template: venues/_entry
    uriFormat: 'venues/{slug}'
type: channel
