defaultPlacement: end
enableVersioning: true
handle: venues
name: Venues
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f957802c-8f19-44d3-a30a-668d452862ac: # Emagine VR Analytics
    enabledByDefault: true
    hasUrls: true
    template: venues/_entry
    uriFormat: 'venues/{slug}'
type: channel
